name: Run AI Model Training Notebook

on:
  push:
    paths:
      - '**.ipynb'             # Runs when notebooks change
      - '**.py'                # Runs when code files change
      - 'requirements.txt'     # Runs when dependencies change
  pull_request:

jobs:
  run-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training notebook
      run: |
        jupyter nbconvert --to notebook --execute notebooks/train_model.ipynb \
          --output executed_train_model.ipynb --ExecutePreprocessor.timeout=1200
